const files={civic_policy_calls:{file:'civic_policy_calls.csv',label:'民間／團體訴求'},candidate_sources:{file:'candidate_sources.csv',label:'候選人政見'}};
let kind='civic_policy_calls',headers=[],rows=[];
const parseCSV=t=>{const out=[];let row=[],cell='',q=false;for(let i=0;i<t.length;i++){const c=t[i],n=t[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++}else if(c==='"')q=!q;else if(c===','&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(x=>x!==''))out.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell);out.push(row)}return out};
const esc=v=>/[",\n\r]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v;
const key=()=>`culture-review-${kind}`;
const saved=()=>JSON.parse(localStorage.getItem(key())||'{}');
const save=(id,value)=>{const s=saved();s[id]={...(s[id]||{}),...value};localStorage.setItem(key(),JSON.stringify(s))};
function render(){const s=saved(),idx=Object.fromEntries(headers.map((h,i)=>[h,i]));count.textContent=`${rows.length} 筆待審來源；已決定 ${Object.keys(s).filter(id=>s[id].status).length} 筆`;document.getElementById('github').href=`https://github.com/daniel9202/culture-governance-observer/edit/main/data/inbox/${files[kind].file}`;document.getElementById('rows').innerHTML=rows.map((r,i)=>{const id=r[idx.source_url]||String(i),v=s[id]||{},title=r[idx.source_title]||'未命名來源',city=r[idx.city]||'',date=r[idx.published_date]||'';return `<article class="review-card"><p class="kicker">${city} · ${date}</p><h2>${title}</h2><p class="muted">${r[idx.source_name]||''}</p><a class="source" href="${r[idx.source_url]}" target="_blank" rel="noopener">開啟原始來源 ↗</a><div class="review-actions"><button class="yes ${v.status==='accepted'?'active':''}" data-id="${i}" data-status="accepted">Yes｜收錄</button><button class="no ${v.status==='rejected'?'active':''}" data-id="${i}" data-status="rejected">No｜不收錄</button></div><label>查核備註<textarea data-note="${i}" placeholder="可寫判斷理由、團體名稱或政策重點">${v.note||''}</textarea></label></article>`}).join('');document.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>{const r=rows[+b.dataset.id],id=r[idx.source_url]||b.dataset.id;save(id,{status:b.dataset.status});render()});document.querySelectorAll('[data-note]').forEach(x=>x.oninput=()=>{const r=rows[+x.dataset.note],id=r[idx.source_url]||x.dataset.note;save(id,{note:x.value})})}
async function load(){kind=document.getElementById('type').value;const res=await fetch(`data/inbox/${files[kind].file}`);[headers,...rows]=parseCSV(await res.text());render()}
document.getElementById('type').onchange=load;
download.onclick=()=>{const idx=Object.fromEntries(headers.map((h,i)=>[h,i])),s=saved();const output=[headers,...rows.map((r,i)=>{const id=r[idx.source_url]||String(i),v=s[id]||{};const a=[...r];a[idx.review_status]=v.status||a[idx.review_status]||'pending';a[idx.review_note]=v.note||a[idx.review_note]||'';return a})].map(r=>r.map(esc).join(',')).join('\r\n')+'\r\n';const url=URL.createObjectURL(new Blob([output],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=files[kind].file;a.click();URL.revokeObjectURL(url)};
load();