const files={civic_policy_calls:{file:'civic_policy_calls.csv'},candidate_sources:{file:'candidate_sources.csv'}};
let kind='civic_policy_calls',headers=[],rows=[],reviewToken='';
const localBridge=['localhost','127.0.0.1'].includes(location.hostname);
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const safeUrl=url=>{try{const parsed=new URL(url);return ['http:','https:'].includes(parsed.protocol)?parsed.href:'#'}catch{return '#'}};
const parseCSV=text=>{const output=[];let row=[],cell='',quoted=false;for(let index=0;index<text.length;index++){const char=text[index],next=text[index+1];if(char==='"'&&quoted&&next==='"'){cell+='"';index++}else if(char==='"')quoted=!quoted;else if(char===','&&!quoted){row.push(cell);cell=''}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&next==='\n')index++;row.push(cell);if(row.some(value=>value!==''))output.push(row);row=[];cell=''}else cell+=char}if(cell||row.length){row.push(cell);output.push(row)}return output};
const escCSV=value=>/[",\n\r]/.test(value)?'"'+value.replace(/"/g,'""')+'"':value;
const key=()=>`culture-review-${kind}`;
const saved=()=>JSON.parse(localStorage.getItem(key())||'{}');
const save=(id,value)=>{const state=saved();state[id]={...(state[id]||{}),...value};localStorage.setItem(key(),JSON.stringify(state))};
const topicGuess=title=>[['文化資產','文資|古蹟|歷史建築|無形文化'],['藝文活動','藝文|藝術|展演|表演'],['文化場館','場館|博物館|美術館|圖書館'],['地方文史','地方文化|文史|記憶'],['文化預算','預算|經費'],['文化教育','文化教育|母語|客語']].filter(([,pattern])=>new RegExp(pattern).test(title)).map(([topic])=>topic).join('|');
const routeForOffice=office=>String(office).includes('議員')?{label:'議員政見頁',url:'councilors.html'}:{label:'縣市長政見頁',url:'mayors.html'};

function publishForm(row,indexByName,index){
  const title=row[indexByName.source_title]||'',url=row[indexByName.source_url]||'',publishedDate=row[indexByName.published_date]||'',note=row[indexByName.review_note]||'',topics=topicGuess(title),common=`<label class="wide">議題分類（以 | 分隔）<input name="topics" value="${escapeHtml(topics)}"></label><label class="wide">公開摘要<textarea name="summary" required>${escapeHtml(note)}</textarea></label>`;
  if(kind==='candidate_sources')return `<form class="publish-form" data-publish="${index}"><h3>上架為候選人政見</h3><label>候選人<input name="candidate" required></label><label>政黨<input name="party" required></label><label>參選職務<select name="office" data-route-office required><option>縣市長</option><option>縣市議員</option></select></label><label>主要來源類型<select name="source_type" required><option>新聞報導</option><option>候選人原文</option><option>政黨官方資料</option><option>政府公開資料</option></select></label><p class="wide route-preview" data-route-preview>確認上架後：將自動歸入「縣市長政見頁」。</p>${common}<label class="wide">政策論述<textarea name="policy_argument" required></textarea></label><label class="wide">政策論述對應來源<textarea name="policy_argument_sources"></textarea><small class="field-help">選填；格式為「標題::網址」，多筆以 || 分隔。留白時會使用主要來源。</small></label><label class="wide">具體主張<textarea name="concrete_proposals" required></textarea><small class="field-help">多項請以 || 分隔。</small></label><label class="wide">具體主張對應來源<textarea name="concrete_proposal_sources"></textarea><small class="field-help">選填；格式為「標題::網址」，多筆以 || 分隔。留白時會使用主要來源。</small></label><label class="wide">相關發言<textarea name="related_statements"></textarea><small class="field-help">只填可核實的發言；多項請以 || 分隔。</small></label><label class="wide">相關發言對應來源<textarea name="related_statement_sources"></textarea><small class="field-help">選填；格式為「標題::網址」，多筆以 || 分隔。留白時會使用主要來源。</small></label><label>主要來源日期<input name="published_date" type="date" value="${escapeHtml(publishedDate)}" required></label><label>主要來源標題<input name="source_title" value="${escapeHtml(title)}" required></label><label class="wide">主要來源網址<input name="source_url" type="url" value="${escapeHtml(url)}" required><small class="field-help">若官網與新聞重複，請把官網放在這裡，新聞會自動移到輔助來源。</small></label><label class="wide">輔助來源網址<textarea name="related_sources"></textarea><small class="field-help">每行一個網址，也可用 | 分隔。</small></label><button class="publish wide" type="submit">確認上架並分流</button></form>`;
  return `<form class="publish-form" data-publish="${index}"><h3>上架為民間政策訴求</h3><p class="wide route-preview">確認上架後：將自動歸入「民間訴求頁」。</p><label>提出者<input name="proposer" required></label><label>提出者類型<select name="proposer_type" required><option value="">請選擇</option><option>民間團體</option><option>公民團體</option><option>協會</option><option>聯盟</option><option>居民</option><option>其他</option></select></label>${common}<label class="wide">具體政策訴求<textarea name="requested_action" required></textarea></label><button class="publish wide" type="submit">確認上架並分流</button></form>`;
}

function render(){
  const stateByUrl=saved(),indexByName=Object.fromEntries(headers.map((header,index)=>[header,index]));
  const rowState=(row,index)=>{const id=row[indexByName.source_url]||String(index),local=stateByUrl[id]||{};return{id,status:local.status||row[indexByName.review_status]||'pending',note:local.note||row[indexByName.review_note]||''}};
  const rejected=rows.filter((row,index)=>rowState(row,index).status==='rejected').length,published=rows.filter((row,index)=>rowState(row,index).status==='published').length;
  const visible=rows.map((row,index)=>({row,index,value:rowState(row,index)})).filter(item=>!['rejected','published'].includes(item.value.status));
  const pending=rows.filter((row,index)=>rowState(row,index).status==='pending').length,accepted=rows.filter((row,index)=>rowState(row,index).status==='accepted').length;
  document.getElementById('count').textContent=`待決定 ${pending} 筆；待上架 ${accepted} 筆；已上架 ${published} 筆；不收錄 ${rejected} 筆`;
  document.getElementById('github').href=`https://github.com/daniel9202/culture-governance-observer/edit/main/data/inbox/${files[kind].file}`;
  document.getElementById('rows').innerHTML=visible.map(({row,index,value})=>{const title=row[indexByName.source_title]||'未命名來源',city=row[indexByName.city]||'',date=row[indexByName.published_date]||'';return `<article class="review-card"><p class="kicker">${escapeHtml(city)} · ${escapeHtml(date)}</p><h2>${escapeHtml(title)}</h2><p class="muted">${escapeHtml(row[indexByName.source_name]||'')}</p><a class="source" href="${escapeHtml(safeUrl(row[indexByName.source_url]))}" target="_blank" rel="noopener">開啟原始來源 ↗</a><div class="review-actions"><button class="yes ${value.status==='accepted'?'active':''}" data-id="${index}" data-status="accepted">Yes｜收錄</button><button class="no" data-id="${index}" data-status="rejected">No｜不收錄</button></div><label>查核備註<textarea data-note="${index}" placeholder="可寫判斷理由、團體名稱或政策重點">${escapeHtml(value.note)}</textarea></label>${value.status==='accepted'?publishForm(row,indexByName,index):''}</article>`}).join('');
  document.querySelectorAll('[data-status]').forEach(button=>button.onclick=()=>review(button,indexByName));
  document.querySelectorAll('[data-note]').forEach(input=>input.oninput=()=>{const row=rows[Number(input.dataset.note)],id=row[indexByName.source_url]||input.dataset.note;save(id,{note:input.value})});
  document.querySelectorAll('[data-route-office]').forEach(select=>select.onchange=()=>{const route=routeForOffice(select.value),preview=select.closest('form').querySelector('[data-route-preview]');preview.textContent=`確認上架後：將自動歸入「${route.label}」。`});
  document.querySelectorAll('[data-publish]').forEach(form=>{const button=document.createElement('button'),hint=document.createElement('small');button.type='button';button.className='prefill wide';button.textContent='抓取原文並預填';hint.className='field-help wide';hint.textContent=kind==='candidate_sources'?'只會填入草稿；請核對內容、補政黨與確認是否為具體政見後再上架。':'只會填入草稿；請核對摘要與訴求，並填寫可確認的提出者與類型後再上架。';button.onclick=()=>prefill(button,form,indexByName);form.querySelector('h3').after(button,hint);if(kind==='civic_policy_calls'){const select=form.elements.namedItem('proposer_type');if(select){const option=document.createElement('option');option.value='文史工作者';option.textContent='文史工作者';select.append(option)}}});
  document.querySelectorAll('[data-publish]').forEach(form=>form.onsubmit=event=>publish(event,form,indexByName));
}

async function review(button,indexByName){const index=Number(button.dataset.id),row=rows[index],id=row[indexByName.source_url]||button.dataset.id,note=document.querySelector(`[data-note="${index}"]`).value;try{if(localBridge){document.getElementById('sync').textContent='正在同步查核決定…';button.disabled=true;const response=await fetch('/api/review',{method:'POST',headers:{'Content-Type':'application/json','X-Review-Token':reviewToken},body:JSON.stringify({kind,source_url:row[indexByName.source_url],status:button.dataset.status,note})});const output=await response.json();if(!response.ok)throw Error(output.error||'同步失敗');document.getElementById('sync').textContent=`已同步 GitHub：${output.commit}`;await load()}else{save(id,{status:button.dataset.status,note});render()}}catch(error){document.getElementById('sync').textContent=`未同步：${error.message}`;alert(`沒有寫入 GitHub：${error.message}`)}}
async function prefill(button,form,indexByName){if(!localBridge){alert('請從本機查核服務執行抓取與預填。');return}const index=Number(form.dataset.publish),row=rows[index];try{button.disabled=true;document.getElementById('sync').textContent='正在抓取原始來源並建立草稿…';const response=await fetch('/api/prefill',{method:'POST',headers:{'Content-Type':'application/json','X-Review-Token':reviewToken},body:JSON.stringify({kind,source_url:row[indexByName.source_url]})});const fields=await response.json();if(!response.ok)throw Error(fields.error||'抓取失敗');Object.entries(fields).forEach(([name,value])=>{const input=form.elements.namedItem(name);if(input&&value)input.value=value});document.getElementById('sync').textContent='已預填草稿；請核對內容、補政黨後再確認上架。'}catch(error){document.getElementById('sync').textContent=`預填失敗：${error.message}`;alert(error.message)}finally{button.disabled=false}}
async function publish(event,form,indexByName){event.preventDefault();if(!localBridge){alert('請從本機查核服務執行自動上架。');return}const index=Number(form.dataset.publish),row=rows[index],fields=Object.fromEntries(new FormData(form)),route=kind==='candidate_sources'?routeForOffice(fields.office):{label:'民間訴求頁',url:'civic.html'},button=form.querySelector('button');try{button.disabled=true;document.getElementById('sync').textContent='正在驗證、產生公開資料並推送 GitHub…';const response=await fetch('/api/publish',{method:'POST',headers:{'Content-Type':'application/json','X-Review-Token':reviewToken},body:JSON.stringify({kind,source_url:row[indexByName.source_url],fields})});const output=await response.json();if(!response.ok)throw Error(output.error||'上架失敗');document.getElementById('sync').innerHTML=`已上架並同步 GitHub：${escapeHtml(output.commit)}。已自動分流到 <a href="${route.url}" target="_blank" rel="noopener">${route.label} ↗</a>`;await load()}catch(error){button.disabled=false;document.getElementById('sync').textContent=`上架失敗：${error.message}`;alert(error.message)}}
async function load(){kind=document.getElementById('type').value;const response=await fetch(`data/inbox/${files[kind].file}?t=${Date.now()}`);[headers,...rows]=parseCSV(await response.text());if(localBridge)document.getElementById('sync').textContent='本機同步模式：可查核並上架已接受的資料。';render()}
async function init(){if(localBridge){const response=await fetch('/api/session',{cache:'no-store'});if(!response.ok)throw Error('無法建立安全的本機查核工作階段');reviewToken=(await response.json()).token}await load()}
document.getElementById('type').onchange=load;
download.onclick=()=>{const indexByName=Object.fromEntries(headers.map((header,index)=>[header,index])),stateByUrl=saved(),output=[headers,...rows.map((row,index)=>{const id=row[indexByName.source_url]||String(index),value=stateByUrl[id]||{},copy=[...row];copy[indexByName.review_status]=value.status||copy[indexByName.review_status]||'pending';copy[indexByName.review_note]=value.note||copy[indexByName.review_note]||'';return copy})].map(row=>row.map(escCSV).join(',')).join('\r\n')+'\r\n',url=URL.createObjectURL(new Blob([output],{type:'text/csv;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download=files[kind].file;link.click();URL.revokeObjectURL(url)};
init().catch(error=>{document.getElementById('sync').textContent=error.message});
